NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path("accounts/", include('allauth.urls')),
    path('subscriptions/', include('subscriptions.urls')),
]

news/urls.py
from django.urls import path

from .views import (
    PostListView, PostDetailView, PostListFilter,
    ArtCreate, ArtEdit, ArtDelete,
    NewCreate, NewEdit, NewDelete
)

app_name = 'news'
urlpatterns = [    
    path('', PostListView.as_view(), name='news'),
    path('<int:pk>/', PostDetailView.as_view(), name='new'),
    path('search/', PostListFilter.as_view(), name='search'),
    # статьи
    path('articles/create/', ArtCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', ArtEdit.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', ArtDelete.as_view(), name='articles_delete'),
    # новости
    path('news/create/', NewCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', NewEdit.as_view(), name='news_edit'),
    path('news/<int:pk>/delete/', NewDelete.as_view(), name='news_delete'),    
]

news/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    """Модель Author
    Модель, содержащая объекты всех авторов.
    Имеет следующие поля:
        +cвязь «один к одному» с встроенной моделью пользователей User;
        +рейтинг пользователя. Ниже будет дано описание того, как этот рейтинг можно посчитать."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating_user = models.IntegerField(default=0)
        
    def update_rating(self):
        """
        Метод update_rating() модели Author, который обновляет рейтинг текущего автора
        (метод принимает в качестве аргумента только self).
        Он состоит из следующего:
            +суммарный рейтинг каждой статьи автора умножается на 3;
            +суммарный рейтинг всех комментариев автора;
            +суммарный рейтинг всех комментариев к статьям автора.
        """ 
        self.rating_user = 0
        #суммарный рейтинг каждой статьи автора умножается на 3
        for i in self.post_set.all().values_list('rating_new'):
            self.rating_user += i[0]
        self.rating_user = self.rating_user*3
        #суммарный рейтинг всех комментариев автора
        for i in Comment.objects.filter(user=User.objects.get(username=self.user.username)).values_list('rating_comment'):
            self.rating_user += i[0]                
        #суммарный рейтинг всех комментариев к статьям автора
        for i in Post.objects.filter(user=self):
            for j in i.comment_set.all().values_list('rating_comment'):
                self.rating_user += j[0]
        self.save()
        
    def __str__(self) -> str:
        return f"{self.user.username}"                
            
        
class Category(models.Model):
    """Модель Category
    Категории новостей/статей — темы, которые они отражают (спорт, политика, образование и т. д.). 
    Имеет единственное поле: 
        +название категории. 
    Поле должно быть уникальным (в определении поля необходимо написать параметр unique = True)."""
    category = models.CharField(max_length=255, unique=True)
    
    def __str__(self) -> str:
        return f"{self.category}"    


class Post(models.Model):
    """Модель Post
    Эта модель должна содержать в себе статьи и новости, которые создают пользователи. 
    Каждый объект может иметь одну или несколько категорий.
    Соответственно, модель должна включать следующие поля:
        +связь «один ко многим» с моделью Author;
        +поле с выбором — «статья» или «новость»;
        +автоматически добавляемая дата и время создания;
        +связь «многие ко многим» с моделью Category (с дополнительной моделью PostCategory);
        +заголовок статьи/новости;
        +текст статьи/новости;
        +рейтинг статьи/новости."""
    article = "A"
    news = "N"
    POST = [(article, "Статья"),
            (news, "Новость")]
    
    post = models.CharField(max_length=1,
                            choices=POST,
                            default=article)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating_new = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through="PostCategory")
    
    def like(self):
        """
        Increases the rating of the post by 1.
        """
        self.rating_new += 1
        self.save()
    
    def dislike(self):
        """
        Increases the rating of the post by -1.
        """
        self.rating_new -= 1
        self.save()
    
    def preview(self):
        """
        Returns the first 124 characters of the post with an ellipsis (...) at the end.

        Parameters:
            self (Post): The current instance of the Post model.

        Returns:
            str: The first 124 characters of the post with an ellipsis (...) at the end.
        """
        if len(self.text) <= 124:
            return self.text
        else:
            return self.text[:124] + "..."
        
    def __str__(self) -> str:
        return f"{self.title} / {self.text[:30]}"
    
    def get_absolute_url(self):
        return reverse('news:new', args=[str(self.id)])


class PostCategory(models.Model):
    """Модель PostCategory
    Промежуточная модель для связи «многие ко многим»:
        +связь «один ко многим» с моделью Post;
        +связь «один ко многим» с моделью Category."""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    

class Comment(models.Model):
    """Модель Comment
    Под каждой новостью/статьёй можно оставлять комментарии, поэтому необходимо организовать 
    их способ хранения тоже.
    Модель будет иметь следующие поля:
        +связь «один ко многим» с моделью Post;
        +связь «один ко многим» со встроенной моделью User (комментарии может оставить 
                                                            любой пользователь, необязательно автор);
        +текст комментария;
        +дата и время создания комментария;
        +рейтинг комментария."""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    rating_comment = models.IntegerField(default=0)
    
    def like(self):
        """
        Increases the rating of the post by 1.
        """
        self.rating_comment += 1
        self.save()
    
    def dislike(self):
        """
        Increases the rating of the post by -1.
        """
        self.rating_comment -= 1
        self.save()
        
    def __str__(self) -> str:
        return f"{self.post.title} / {self.text[:20]}"
    

news/forms.py
from django import forms

from .models import Post

class PostArticleCreate(forms.ModelForm):
    
    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     # project = Project.objects.get(slug=self.kwargs['project_slug'])
    #     # form.instance.project = project
    #     return super(self).form_valid(form) #ResponseCreate, перед self
    
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['field'].initial = 'z'
    
    class Meta:
        model = Post
        fields = ['title', 'text', 'categories']
        

news/views.py
import datetime
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

#from news.tasks import hello для эксперемента
# from requests import request

from .models import Author, Post
from .filters import NewsFilter
from .forms import PostArticleCreate
from pprint import pprint 

class PostListView(ListView):
    """Сделайте новую страничку с адресом /news/, на которой должен выводиться список всех новостей."""
    # Указываем модель, объекты которой мы будем выводить
    model = Post
    # Поле, которое будет использоваться для сортировки объектов
    ordering = '-date_added'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'news.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'news'
    paginate_by = 10 # количество записей на странице
    
    #функция для отработки celery
    """def get(self, request):
        hello.delay()
        return HttpResponse('Hello!')"""
    
    
class PostListFilter(ListView):
    # Указываем модель, объекты которой мы будем выводить
    model = Post
    # Поле, которое будет использоваться для сортировки объектов
    ordering = '-date_added'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'news_filter.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'news'
    paginate_by = 10 # количество записей на странице
    
    # Переопределяем функцию получения списка статей(новостей)
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = NewsFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список статей(новостей)
        return self.filterset.qs
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       # Добавляем в контекст объект фильтрации.
       context['filterset'] = self.filterset
       #context['time_now'] = datetime.utcnow()
       return context
    

class PostDetailView(DetailView):
    """Сделайте отдельную страничку для конкретной новости по адресу /news/<id новости>"""
    model = Post
    # Используем другой шаблон — new.html
    template_name = 'new.html'
    # Название объекта, в котором будет выбранный пользователем пост.статья
    context_object_name = 'new'    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Post.objects.get(pk=self.kwargs['pk']).categories.values_list('category', flat=True)
        return context
    

class ArtCreate(PermissionRequiredMixin, CreateView):
    raise_exception = True
    permission_required = ('news.add_post',)
    # Указываем нашу разработанную форму
    form_class = PostArticleCreate
    # модель статьи
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'postartcreate.html'
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = Author.objects.get(user=self.request.user)
        instance.save()
        
        return super().form_valid(form)
    
    
# Добавляем представление для изменения статьи.
class ArtEdit(PermissionRequiredMixin, UpdateView):
    raise_exception = True
    permission_required = ('news.change_post',)    
    form_class = PostArticleCreate
    model = Post
    template_name = 'postartcreate.html'
    
    
class ArtDelete(PermissionRequiredMixin, DeleteView):    
    raise_exception = True
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'article_delete.html'
    success_url = reverse_lazy('news:news')
    
    
class NewCreate(PermissionRequiredMixin, CreateView):
    raise_exception = True
    permission_required = ('news.add_post',)
    # Указываем нашу разработанную форму
    form_class = PostArticleCreate
    # модель товаров
    model = Post
    # и новый шаблон, в котором используется форма.
    template_name = 'postartcreate.html'
    
    # def form_valid(self, form):
    #     news = form.save(commit=False)
    #     news.post = 'news'
    #     return super().form_valid(form)
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        # print(self.request.user)
        instance.user = Author.objects.get(user=self.request.user)
        instance.post = 'news'
        instance.save()
        
        return super().form_valid(form)
    
    
    
class NewEdit(PermissionRequiredMixin, UpdateView):
    raise_exception = True
    permission_required = ('news.change_post',)
    form_class = PostArticleCreate
    model = Post
    template_name = 'postartcreate.html'
    
    
class NewDelete(PermissionRequiredMixin, DeleteView):
    raise_exception = True
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'article_delete.html'
    success_url = reverse_lazy('news:news')

news/templates/news/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        
        {% load static %}
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="">Newspaper</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/news/">Home
                                <span class="sr-only">(главная)</span>
                            </a>
                        </li>
                        {% if request.user.username %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">log out</a>
                        </li>
                        {% endif %}
                        {% if not request.user.username %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">log in(signup)</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="">{{ request.user.username }}</a>
                        </li>
                        {% endif %}
                        {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
                        {% if perms.news.add_post %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:news_create' %}">Добавить новость</a>
                        </li>
                        {% endif %}
                        {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
                        {% if perms.news.add_post %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:articles_create' %}">Добавить статью</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'news:search' %}">Поиск</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'subscriptions' %}">Подписки</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
         </nav>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    {% block content %}
                    <!-- {{ flatpage.content }} -->
                    {% endblock content %}
                </div>
            </div>
         </div>
    </body>